### ISSUE TITLE
Copper might remove too much responses when a workflow instances finishes

### ISSUE THREAD

**Issue by jharabasz** [copper-engine/copper-engine#62]
When a workflow finished Copper will remove all responses with a CorrelationId that was used in the last "wait()" call.

Copper will remove those responses even if they were received after the last "wait()" and though never processed by the workflow. 

It would be helpful if Copper would only delete those responses that were actually received by the workflow, when the workflow finishes.

**Comment by austermann** [comment]
The problem occurs only in the following situation:

1. Workflow instance A is waiting for responses with correlationId X.
2. Workflow instance A wakes up and processes the responses for X.
3. Meanwhile more respones with correlationId X arrive
4. Workflow instance A finishes, so COPPER will remove ALL responses with correlationId X - also those arrived in step 3
5. Workflow instance B is started and waits for responses with correlationId X.
6. Workflow instance B will not receive the resposes from step 3, because they have been deleted in step 4.

The fix is quite simple:
When a workflow instance finishes, copper will only remove those respones that have been processes for the workflow instance so far. Their responseIds are already available, see `PersistentWorkflow.responseIdList`
