### ISSUE TITLE
where is the mysql tables‘ initialization DDL when using the PersistentWorkflow

### ISSUE THREAD

**Issue by ArduousBonze** [copper-engine/copper-engine#69]
I am using the PersistentWorkflow with mysql, but when i try to start a PersistentScottyEngine. I got below error:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dtb_tangram.cop_response' doesn't exist
```

I think there is ddl for initialize db before start an engine. Where can i find it.  Thank you!

**Comment by austermann** [comment]
Hi! 

It's here: 
https://github.com/copper-engine/copper-engine/blob/master/projects/copper-coreengine/src/main/database/mysql/create-schema.sql 

Cheers, 
Michael 



Von: "michael.wc" <notifications@github.com> 
An: "copper-engine/copper-engine" <copper-engine@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Donnerstag, 16. Februar 2017 07:00:34 
Betreff: [copper-engine/copper-engine] where is the mysql tables‘ initialization DDL when using the PersistentWorkflow (#69) 



I am using the PersistentWorkflow with mysql, but when i try to start a PersistentScottyEngine. I got below error: 
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dtb_tangram.cop_response' doesn't exist 


I think there is ddl for initialize db before start an engine. Where can i find it. Thank you!

**Comment by ArduousBonze** [comment]
Thank a lot!
