### ISSUE TITLE
YamlSerializer cannot handle final fields

### ISSUE THREAD

**Issue by austermann** [copper-engine/copper-engine#75]
Reported by Howie:
It turns out the SnakeYaml library have problem serialize enum types in the Data, they become null. This is kinda dangerous...

**Comment by theoWork** [comment]
I cannot reproduce this issue. If I put an enum like this 

```
public enum StupidEnum {
    FAHRENHEIT,
    CELSIUS,
    KELVIN
}
```
as data object to a workflow (with data value as `CELSIUS`) on launch, change it within the workflow to `FAHRENHEIT` by setData() method and call afterwards wait(), I see in my database:
```
!!org.copperengine.examples.exampleApplications.StupidEnum 'FAHRENHEIT'
```
Deserialization works as expected and I can continue to work with the enum on 'FAHRENHEIT'. 

Could you provide an example with this bug?

**Comment by atomic-t** [comment]
It's actually caused by "final" fields inside my Data class so it don't have setter on my class. So for a serializer using reflection it will not work...
Java Serialization won't have such a problem though, I guess this is something the user should know.

----------------------------- 
public class TestData
{
    private int aNumber;
    private final int finalNumber = 42; //this also won't show up
    private final TimeUnit timeUnit = TimeUnit.SECONDS; //or put in default constructor
    private String someString;

...setters & getters
}

 public static void main(String[] args) throws Exception {
        TestData data = new TestData();
        data.setaNumber(1111);
        data.setSomeString("aaaaa");

        Yaml yaml = new Yaml();
        String s = yaml.dump(data);
        System.out.println(s);
}


!!com.test.TestData {aNumber: 1111, someString: aaaaa}
---------------------------------------------------------------------------------------------

Also if a class doesn't have a default constructor this will happen when deserializing: 

        TestData data = new TestData(TimeUnit.SECONDS); 
        data.setaNumber(1111);
        data.setSomeString("aaaaa");

        Yaml yaml = new Yaml();
        String s = yaml.dump(data);
        System.out.println(s);

        TestData data2 = (TestData) yaml.load(s);  ->  Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchMethodException: com.test.TestData.<init>()

**Comment by theoDiefenthal** [comment]
Well, this is kind of a problem for all Serializer and not at all related to COPPER. It's quite difficult to deserialize an object with final fields without a default constructor. The problem here is not having a default constructor. (Setting a final field via reflection is a rather easy task, at least if it is not a static final field where it can become impossible as those contents may be inlined in code. So you could technically change the value but practically it wouldn't have an effect in the code). 

It is possible to construct such objects as the Java default Serializer already demonstrates. Java uses the `sun.misc.Unsafe` class to construct objects without a constructor. For a nice problem description and overview, see: http://www.externalizer4j.com/how-java-serialization-deserializes-final-fields

The bottom line of this is, this kind of special classes which you mention need to be deserialized in a rather special way. If I take a look at the SnakeYAML sources, there is no usage of Unsafe or Objenesis (A library often used in this context as it is not easy to get an instance of the Unsafe class and the way to get it is platform and JVM dependent. So Objenesis does the annoying stuff and internally makes the Unsafe calls). SnakeYAML seems to always search for the default constructor.

I will, however, make a change to the COPPER code for our serializer after I took a closer look into SnakeYAML library. By setting `yaml.setBeanAccess(BeanAccess.FIELD);`, all fields get serialized and not only Bean like or public fields, so also private field contents get serialized as well. I think, this is a valid extension in our kind of usage. For instance, if I have a class like this:
```
public class TestData {
    private final long timestamp;
    public TestData()
    {
        this.timestamp = System.currentTimeMillis();
    }
}
```
I really want the timestamp to be serialized and deserialized afterwards...

But back to the topic: It is to mention that there are Serialization libraries next to the default Java Serialization which are capable of handling those special classes. I think, to name are Kryo (Which uses Objenesis) and Jackson. Kryo has its own highly efficient scheme, which is not human readable afterall... And they also state that they can't handle all cases of classes for serialization so that they sometimes fall back to Java serialization. This demonstrates the complexiness of the Serialization-mechanism as Kryo is a rather advanced library and is used in many big projects such as Apache Spark. Jackson in turn offers a YAML Serialization output format as option. I never worked with Jackson but I think, handling those special classes is also not that easy with Jackson.

We now could give Jackson a try and just switch the SnakeYaml code to Jackson. But I think, this leads to  a lot of tests wheter this change wouldn't break existing serialized datasets.  I could imagine, these libraries treat naming differently (An enum for instance could be written down in different ways) and testing compatibility everywhere is quite a heavy and in my opinion not worthy task. 

So if you have this kind of special classes in your project, my recommondation for you is to test out Jackson as Serializer. Take our YamlSerializer as example on how easy it is to switch to a new Serializer and then hopefully find a Serialization library which handles your classes correctly. Or if possible, just rewrite your classes in a way that they can be serialized. 

As I think this is not a bug or problem of COPPER itself and can't be solved from us, I close the ticket. If you tested out Jackson (or another Serializer) and solved your problem, I would be happy if you leave a message on the mailing list. For sure, I'm happy for any other notes on this topic as well, but I think this is more a mailing list topic.
