### ISSUE TITLE
Rowid is used as primary key for Table COP_QUEUE

### ISSUE THREAD

**Issue by FabianHo1** [copper-engine/copper-engine#76]
The Trigger COP_BP_INSERT_TRIGGER uses new.rowid for WFI_ROWID while inserting into Table COP_QUEUE.
COP_QUEUE uses WFI_ROWID as part of an composite primary key. According to the oracle documentation a rowid is not supposed to be used as primary key because ["If you delete a row, then Oracle may reassign its rowid to a new row inserted later"](https://docs.oracle.com/cd/B19306_01/server.102/b14200/pseudocolumns008.html). This reassignment did cause a unique constraint violation in our project (in production) and thus stopped every attempt of starting an new copper workflow .

**Comment by theoWork** [comment]
In the special case of our usage (using rowid as primary key for a queue), this can't be a problem as there can't be two physical queue entries at the same position at one time. 

The only case where one of us can imagine a problem arising due to this design is if you use more than one engine  on a single data base without setting the multi engine mode. If the multi engine mode is not set, no lock is required for transactions on the database where it could happen that two engines would like to write simultaneously to the queue and thus want to write to the same physical address (row id) resulting in a duplicate id exception in COP_QUEUE as the row id needs to be uniquely used (primary key). 

So make sure that you either don't have multi engines running on a single data base or that you enable multi engine mode in your application for all engines used. 

This error can further occur only when using the "old" OracleDialect. In COPPER, there is also a new "SimpleOracleDialect" implemented which is recommended to be used as we might remove the old OracleDialect in future. 

I hope, I cited Michael quite correctly who gave me this answer verbally. 

The issue can thus be closed as it is not a COPPER bug but results out of a wrong usage of COPPER.
